<?php

/**
 * Created by PhpStorm.
 * User: a.verizhnikov
 * Date: 01.08.2016
 * Time: 16:44
 */
namespace app\components;
use yii\base\Widget;
use app\models\Category;

class MenuWidget extends Widget
{
    public $tpl;
    public $model;
    public $data;
    public $tree;
    public $menuHtml;


    public function  init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->tpl === null){
            $this->tpl = 'menu';
        }
        $this->tpl.='.php';
    }

    public function run()

    {
//        if($this->tpl == 'menu.php'){
//            $menu = Yii::$app->cache->get('menu');
//            if($menu) return $menu;
//        }

        $this->data = Category::find()->indexBy('id')->asArray()->all();
        $this->tree = $this->getTree();
        $this->menuHtml = $this->getMenuHtml($this->tree);
        //set cache
//        if($this->tpl == 'menu.php'){
//            Yii::$app->cache->set('menu',$this->menuHtml,60);
//        }

        return $this->menuHtml;
    }

    protected function getTree(){
        $tree = [];
        foreach ($this->data as $id=>&$node){
            if (!$node['parent_id'])
                $tree[$id] = &$node;
            else
                $this->data[$node['parent_id']]['childs'][$node['id']] = &$node;
        }
        return $tree;
    }

    protected function catToTempate($category, $tab){
        ob_start();
        include __DIR__.'/menu_tpl/'.$this->tpl;
        return ob_get_clean();
    }

    protected function getMenuHtml($tree, $tab = ''){
        $str = '';
        $str .= '<ul>';
        foreach ($tree as $category){
            $str.=$this->catToTempate ($category, $tab);
        }
        $str .= '</ul>';
        return $str;
    }




}